### ISSUE TITLE
Update solana deps to 1.14.3

### ISSUE THREAD

**Issue by aspnxdd** [VegetarianOrc/shadow-drive-rust#28]
I think the solana-client dependency could be updated since it is 3 months old and some libraries that require new versions of tokio cant be run.

I was trying to build on [shuttle](https://www.shuttle.rs/) and was getting this error 
![image](https://user-images.githubusercontent.com/43625217/193092856-4127718d-9b39-44bf-99f3-8a3a8c66f370.png)

Shuttle requires a tokio version > 1.21.*. While solana-client (v1.10.29) has a hard lock on tokio 1.14.1...

Probably the other solana deps in 1.10.29 could also be upgraded!

> solana-client = "~1.10.29"
> solana-transaction-status = "~1.10.29"
> solana-account-decoder = "~1.10.29"
> solana-sdk = "~1.10.29"

**Comment by VegetarianOrc** [comment]
Hey there! Thanks for the suggestion! 

Unfortunately this SDK relies on the Shadow Drive User Staking crate which depends on Anchor which in turn depends on a specific version of the Solana dependencies.

If/when the folks over at GenesysGo update to a new version of Anchor we'll revisit upgrading.
